language: java
before_install:
  - mkdir -p target/parent-pom
  - git clone git://github.com/ctrimble/parent-pom.git target/parent-pom
  - pushd target/parent-pom
  - mvn install
  - popd
notifications:
  email:
    - christian.trimble@meltmedia.com
